### ISSUE TITLE
how can i get T

### ISSUE THREAD

**Issue by jaccen** [rodolfoap/screen2world-k#1]
TVec:
[-1.901595961898777;
 -43.58726706166781;
 -0.1164105524075865]

how can l get this?
3ks

**Comment by rodolfoap** [comment]
Build the application and run this (which is shown on the `.x` file)
```
./gen-extrinsic test/camera_matrix_1280x720.yaml test/points_matrix.yaml
```

**Comment by jaccen** [comment]
i know your method ,but  i want to know ,if i could not get the points like yours (pixel--->world).  i only know the position of my camera in  longitude and latitude  and get the camera's R from IMU,  and calibrate the K (inner Matrix),    the  how can l get the T,
or  how can l get the any pixel to  the word position?
